site_name: NAT Docs
site_url: https://natindonesia.github.io/architect

theme:
  name: material
  features:
    - navigation.instant
    - content.code.copy
plugins:
  - tags
  - search
  - social
markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format